spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/springboottest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
logging:
  config: classpath:log4j2.xml
#mybatis:
  #如果有多个目录则可以写多个，比如com/best/dao/*.xml，com/best/*/dao/*.xml,com/best/*/sss/*/dao/*.xml
#  mapper-locations: classpath:com/best/dao/*.xml
  #配置包，这里同样可以配置多个，
#  type-aliases-package: com.best.dao
#logging:
#  level:
 #   com.best.dao: trace
mybatis-plus:
  # 如果是放在src/main/java目录下 比如com/best/dao/*.xml，com/best/*/dao/*.xml,com/best/*/sss/*/dao/*.xml
  # 如果是放在resource目录 classpath:com/best/dao/*.xml
  mapper-locations: classpath:com/best/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.best.mapper
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"

    #驼峰下划线转换
    db-column-format: true
    #刷新mapper 调试神器
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true

server:
  port: 8080
